INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('My day has been _______.', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Something I regret.', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('What stands between you and happiness?', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('The first thing that comes to mind when you hear the word \"joy\".', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('If you had no constraints whatsoever, what would you be doing right now?', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Describe your ideal life in 5 years. Then describe your life in 5 years realistically.', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('One thing you’re grateful for.', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Sometimes I just stop and think ____________.', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('What movie can you watch over and over without getting tired of?', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('What do you think is my favourite genre of music?', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('What do you think I do in my spare time?', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('What do you think I’d be doing right now if COVID didn’t exist?', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Describe your craziest experience.', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Do you think I fall in love easily? Why or why not?', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('If I had a superpower, it would be ___________.', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Share a vivid memory from your childhood.', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Make an assumption about me.', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Share the first thought you had when you entered this call with me.', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('What do you think was my best and worst subject in school?', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('How do you think I express myself?', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('What kind of photos do you think my photo album is filled with?', '1');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Your first impression of me.', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Honestly, I just want to say ______.', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('You think I ________.', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Random thought.', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('I wish I had ________.', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('One thing you think I should hear.', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('One trait I have that you’d like to inherit.', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('One thing I would like to do with you after this talk.', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('What is one thing about you that most people don’t know about?', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Shuffle the music in your music library. Explain why you added the first song that comes up.', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('What is one thing your younger self wouldn’t believe about your current self?', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('What makes you happy?', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('Are you happy?', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('How have you really been feeling about the current situation?', '2');
INSERT INTO `reconnect`.`questions` (`qn_string`, `qn_rating`) VALUES ('What is one thing you’re still struggling to learn?', '2');